import java.net.*;
import java.io.*;

/**
 * A class that stores every user in the queue with a cost generated by the class 
 *
 */
public class UserNode {
	
	String UserID;
	DummyGPSLocationVar UserRequestStartLocation;
	DummyGPSLocationVar UserRequestDestination;
	boolean isCarpool;
	boolean isEventRequest;
	boolean isAccepted;
	int currentCost;
	int timeCost = 30;
	int userCost = 0; 


	public UserNode(String id, DummyGPSLocationVar start, DummyGPSLocationVar end,
			boolean isShared, boolean forEvent, boolean isAcc ) {
		this.UserID = id;
		this.UserRequestStartLocation = start;
		this.UserRequestDestination = end;
		this.isCarpool = isShared;
		this.isEventRequest = forEvent;
		this.isAccepted = isAcc;
	}
	
	//Getters and Setters:
	public String getUserID() {
		return UserID;
	}

	public void setUserID(String userID) {
		UserID = userID;
	}

	public DummyGPSLocationVar getUserRequestStartLocation() {
		return UserRequestStartLocation;
	}

	public void setUserRequestStartLocation(DummyGPSLocationVar userRequestStartLocation) {
		UserRequestStartLocation = userRequestStartLocation;
	}

	public DummyGPSLocationVar getUserRequestDestination() {
		return UserRequestDestination;
	}

	public void setUserRequestDestination(DummyGPSLocationVar userRequestDestination) {
		UserRequestDestination = userRequestDestination;
	}

	public boolean isAccepted() {
		return isAccepted;
	}

	public void setAccepted(boolean isAccepted) {
		this.isAccepted = isAccepted;
	}

	public int getCurrentCost() {
		return currentCost;
	}

	public void setCurrentCost(int currentCost) {
		this.currentCost = currentCost;
	}
	
	public boolean isCarpool() {
		return isCarpool;
	}

	public void setCarpool(boolean isCarpool) {
		this.isCarpool = isCarpool;
	}

	public boolean isEventRequest() {
		return isEventRequest;
	}

	public void setEventRequest(boolean isEventRequest) {
		this.isEventRequest = isEventRequest;
	}
	
	public int getTimeCost() {
		return timeCost;
	}

	public void setTimeCost(int timeCost) {
		this.timeCost = timeCost;
	}

	public int getUserCost() {
		return userCost;
	}

	public void setUserCost(int userCost) {
		this.userCost = userCost;
	}

	//Generates Costs:
	//Not time bound:
	public int distanceFromDriverCost(DummyGPSLocationVar driverLocation) {
		
		///////NEED MAP API////////
		int distanceBetweenTwoLocations = 0; //some method that gets the distance between the user and the driver in miles  
		// if the distance is less than 10, 
		if (distanceBetweenTwoLocations > 10) {
			//max cost set to 50
			return 50;
		}
		else {
			return 50 - 5 * (int)(10 - distanceBetweenTwoLocations);
		}
	}

	//Evaluation Function (time bounded)
	public int UserCost (DummyGPSLocationVar driverLocation) {
		if (this.isCarpool == false) {
			this.setUserCost(this.getUserCost() + 10);
			}
		if (this.isEventRequest == false) {
			this.setUserCost(this.getUserCost() + 10);
		}
		this.setUserCost(this.getUserCost() + this.distanceFromDriverCost(driverLocation) + this.getTimeCost());
		currentCost = getUserCost();
		return getUserCost();
	}

}
